<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DJ" failures="2" tests="3" name="Test6" time="59.342" errors="0" timestamp="2021-12-22T16:51:53 IST">
  <testcase classname="qtrecog.testcases.ActivityPanel" name="verifyKudosFromMe" time="0.882">
    <failure type="java.lang.AssertionError" message="Kudos from me section is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Kudos from me section is not displayed expected [true] but found [false]
at qtrecog.testcases.ActivityPanel.verifyKudosFromMe(ActivityPanel.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyKudosFromMe -->
  <testcase classname="qtrecog.testcases.ActivityPanel" name="verifyKudosToMe" time="0.181">
    <failure type="java.lang.AssertionError" message="Kudos to me section is not displayed expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Kudos to me section is not displayed expected [true] but found [false]
at qtrecog.testcases.ActivityPanel.verifyKudosToMe(ActivityPanel.java:49)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- verifyKudosToMe -->
  <testcase classname="qtrecog.testcases.ActivityPanel" name="verifyActivity" time="5.54"/>
</testsuite> <!-- Test6 -->
